name: Run VNC Serveo

on:
  workflow_dispatch:

jobs:
  start_vnc:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run VNC Serveo PowerShell script
        shell: pwsh
        run: |
          Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
          .\start-vnc-serveo-pnp.ps1
