
name: Windows noVNC with Pagekite

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      PAGEKITE_RC: ${{ github.workspace }}\pagekite.rc
    steps:
    - name: Install Python and websockify
      run: |
        choco install python --pre -y
        python -m pip install --upgrade pip
        python -m pip install websockify

    - name: Download noVNC
      run: |
        Invoke-WebRequest https://github.com/novnc/noVNC/archive/refs/heads/master.zip -OutFile novnc.zip
        Expand-Archive novnc.zip -DestinationPath .
        Move-Item noVNC-master noVNC

    - name: Install TightVNC
      run: |
        Invoke-WebRequest https://www.tightvnc.com/download/2.8.81/tightvnc-2.8.81-gpl-setup-64bit.msi -OutFile tvnc.msi
        msiexec /i tvnc.msi /quiet
        reg add "HKCU\Software\TightVNC\Server" /v Password /t REG_BINARY /d 31323334353600 /f
        reg add "HKCU\Software\TightVNC\Server" /v AlwaysShared /t REG_DWORD /d 1 /f

    - name: Download Pagekite
      run: |
        Invoke-WebRequest https://pagekite.net/pk/pagekite.py -OutFile pagekite.py

    - name: Create Pagekite config
      run: |
        echo kitename = rdp123.1602studio.pagekite.me > pagekite.rc
        echo kitesecret = Adamzrashwan_161 >> pagekite.rc
        echo service_on = http:6080:localhost:6080 >> pagekite.rc

    - name: Start noVNC server
      run: |
        Start-Process python -ArgumentList "-m websockify 6080 localhost:5900" -NoNewWindow
        Start-Sleep -Seconds 5

    - name: Start Pagekite tunnel
      run: |
        python pagekite.py --clean rdp123.1602studio.pagekite.me
